name: Settle
options:
  minimumXcodeGenVersion: 2.39.0
  createIntermediateGroups: true
  xcodeVersion: "15.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.settle
    DEVELOPMENT_TEAM: ""
    INFOPLIST_FILE: Settle/Info.plist
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    TARGETED_DEVICE_FAMILY: 1
    SWIFT_VERSION: 5.9
packages: {}
targets:
  Settle:
    type: application
    platform: iOS
    sources:
      - path: Settle
    settings:
      base:
        PRODUCT_NAME: Settle
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
    scheme:
      testTargets: []