default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    scan(
      scheme: "Settle",
      devices: ["iPhone 16 Pro"],
      clean: true
    )
  end

  desc "Upload build to TestFlight"
  lane :beta do
    build_app(
      scheme: "Settle",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      distribute_external: true,
      groups: ["Internal Testers"]
    )
  end
end
