name: iOS App Store Release

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: Release notes for App Store submission
        required: false
        default: "Release build"
  push:
    tags:
      - 'ios-release-v*'

jobs:
  appstore-release:
    runs-on: macos-14
    defaults:
      run:
        working-directory: settle-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Generate Xcode project
        uses: xcodegenapp/xcodegen-action@v3
        with:
          version: '2.39.0'
          spec: 'project.yml'

      - name: Export App Store Connect API key env
        shell: bash
        run: |
          echo "APP_STORE_CONNECT_KEY_ID=${{ secrets.APP_STORE_CONNECT_KEY_ID }}" >> $GITHUB_ENV
          echo "APP_STORE_CONNECT_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}" >> $GITHUB_ENV
          echo "APP_STORE_CONNECT_PRIVATE_KEY=${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY_B64 }}" >> $GITHUB_ENV

      - name: Release to App Store (Fastlane)
        env:
          FL_RELEASE_NOTES: ${{ github.event.inputs.release_notes || 'Release build' }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BRANCH: ${{ secrets.MATCH_GIT_BRANCH }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY_B64 }}
          APP_IDENTIFIER: com.example.settle
        run: bundle exec fastlane release
